name: Build and deploy docker image

on:
  push:
    tags:
      - 'v*

env:
  COMPOSE_PATH: ${{ vars.COMPOSE_PATH }}

permissions:
  contents: read

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ja7adr/meilisearch-mcp:latest
            ja7adr/meilisearch-mcp:${{ github.ref_name }}   # e.g. v1.2.3

  deploy:
    needs: build-and-push-image
    runs-on: mcp-deploy
    env:
      COMPOSE_PATH: ${{ env.COMPOSE_PATH }}
    steps:
      - name: Pull latest image
        run: docker pull ja7adr/meilisearch-mcp:latest

      - name: Restart service
        run: docker compose -f "$COMPOSE_PATH" up -d --force-recreate

      - name: Service status
        run: docker compose -f "$COMPOSE_PATH" ps
