name: Testing and coverage

on:
  pull_request:
  merge_group:
  push:
    branches:
      - main

jobs:
  linter:
    name: linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: 1.24
      - uses: actions/checkout@v4
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.64.8
      - name: Run go vet
        run: go vet ./...
      - name: Run fmt and linter
        run: make check-all

  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go ${{ matrix.go }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}

      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Get dependencies
        run: go mod download

      - name: Run tests
        run: |
          go test --race -v -gcflags=-l -coverprofile=coverage.txt -covermode=atomic ./...

      - name: Upload coverage report
        uses: codecov/codecov-action@v5
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
